In [1]:
import cv2

In [2]:
cam=cv2.VideoCapture(0)

In [3]:
status,photo=cam.read()
print(status)

True


In [4]:
cv2.imshow("my_photo",photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
cam.release()

In [6]:
print(photo)

[[[187 198 196]
  [185 196 194]
  [186 195 194]
  ...
  [187 190 191]
  [184 189 191]
  [181 187 189]]

 [[187 197 197]
  [187 196 196]
  [187 195 195]
  ...
  [184 188 187]
  [182 188 187]
  [181 188 188]]

 [[188 197 198]
  [188 196 197]
  [188 196 197]
  ...
  [183 188 183]
  [184 190 186]
  [185 191 187]]

 ...

 [[149 149 149]
  [148 148 148]
  [148 148 148]
  ...
  [170 105  47]
  [168 103  47]
  [168 103  48]]

 [[150 150 150]
  [149 149 149]
  [149 149 149]
  ...
  [171 104  45]
  [170 104  45]
  [169 104  46]]

 [[148 148 148]
  [147 147 147]
  [147 147 147]
  ...
  [170 103  42]
  [169 102  42]
  [169 103  44]]]


In [7]:
print(type(photo))

<class 'numpy.ndarray'>


In [8]:
print(photo.ndim)

3


In [9]:
print(photo.shape)

(480, 640, 3)


In [10]:
print(photo[10,15])

[186 200 196]


In [11]:
print(photo[0:50,20:100])

[[[189 198 197]
  [191 199 198]
  [191 201 199]
  ...
  [196 208 206]
  [197 209 206]
  [200 211 206]]

 [[190 198 197]
  [192 200 199]
  [192 202 200]
  ...
  [197 209 207]
  [199 210 207]
  [199 211 206]]

 [[190 198 197]
  [192 200 199]
  [191 201 199]
  ...
  [198 209 207]
  [199 210 207]
  [199 211 206]]

 ...

 [[190 200 194]
  [190 199 193]
  [190 199 195]
  ...
  [197 207 207]
  [198 208 206]
  [198 208 206]]

 [[186 199 193]
  [187 199 193]
  [189 201 195]
  ...
  [197 209 207]
  [196 209 206]
  [197 209 206]]

 [[185 200 193]
  [186 201 194]
  [188 201 195]
  ...
  [196 210 205]
  [195 209 204]
  [195 209 204]]]


In [12]:
photo[190:480,390:640]=photo[110:400,200:450]

In [13]:
cv2.imshow("my_photo",photo)
cv2.waitKey()
cv2.destroyAllWindows()